name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */3 * *' # mỗi 3 ngày
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -L -X GET \
          'https://jjtfazrvhlontuotqzfn.supabase.co/rest/v1/' \
          -H 'apikey: ${{ secrets.SUPABASE_KEY }}'